name = "gleam_cowboy"
version = "0.7.0"
licences = ["Apache-2.0"]
description = "Run Gleam HTTP services with the Cowboy web server"
gleam = ">= 1.0.0"

repository = { type = "github", user = "gleam-lang", repo = "cowboy" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.31"
gleam_http = "~> 3.0"
gleam_otp = "~> 0.7"
cowboy = "~> 2.5"
gleam_erlang = "~> 0.22"

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_hackney = "~> 1.0"
